# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d9aec249de4e799568a4dff7a074a9600113dcf4611a140d2fc19d992880945c825201acbe9a318a236c10e2f9ca9f6a9a034891b84eb012a6e8a4f387d7048

test:
  secret_key_base: ddbb3d02f6c083030690f0bc89048a4a7b3751c4c6bd3d41a302839ca486dd444c1d424ddf48d7b007b3a8c87a085fa427e25c0695234c0e58bf225464d1fe60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
